### ISSUE TITLE
Endpoint for the data provider (9164)

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis-proxy#44]
So far, when uploading with TUS, the clients receive a Location header that usually points directly to the port 9164

As far as I understand in deployment scenarios where the proxy is used, we'd want to have that one also routed through the proxy.

We could provide an endpoint "/data" and forward it to 9164.

@butonic does that make sense ?

**Comment by PVince81** [comment]
the default config will also need to be adjusted to make sure the Location header points at the proxy

**Comment by PVince81** [comment]
it seems that with EOS the port would be 9160 but for OC data it's 9164, so it might need multiple routes ?

**Comment by PVince81** [comment]
as discussed with @felixboehm, we must provide this to have everything accessible behind a single port

**Comment by butonic** [comment]
reva has a datagateway service which we are starting with ocis-reva as part of the frontend cmd. Three things need to be configured to have everything routed through a single entrypoint:
1. the storage providers need to be configured to never expose a dedicated storage driver. this can be done by setting `REVA_STORAGE_(EOS|HOME|OC)_EXPOSE_DATA_SERVER` to false. This will make the reva gateway use the datagateway instead of the dataproviders directly.
2. the reva gateway needs to use the proxy as the frontend url. try setting REVA_FRONTEND_URL to the outside address (host and port) ... 
  - there may be config problems because [the ocs endpoint prefixes `REVA_FRONTEND_URL`  with `https://`](https://github.com/owncloud/ocis-reva/blob/f5272f3828155db505e8f5932b4f5ae24dd88be6/pkg/command/frontend.go#L116) to construct the ocs.config.host property while [the ocis-reva gateway uses `REVA_FRONTEND_URL` as the datagateway](https://github.com/owncloud/ocis-reva/blob/f5272f3828155db505e8f5932b4f5ae24dd88be6/pkg/command/gateway.go#L111), which [expects a url](https://github.com/cs3org/reva/blob/1b3eb5608cbef3f9244a2037767729356c958099/internal/grpc/services/gateway/gateway.go#L95)
3. ocis-proxy should proxy `/data` to the ocis frontend

**Comment by PVince81** [comment]
as I understand this will be:

-> proxy (port?) -> datagateway (port?) -> OC storage 9164
-> proxy (port?) -> datagateway (port?) -> EOS storage 9160
